name: Build and Deploy to EKS

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "helm/**"
      - ".github/workflows/deploy.yml"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER: eks
  ECR_REPOSITORY: eks-devops-assignment-hello-world
  HELM_RELEASE: hello-world
  K8S_NAMESPACE: hello-world

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::362339782357:role/GitHubActionsEKSDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            ./app

      - name: Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER

      - name: Verify EKS access
        run: |
          kubectl get deployment \
            -n $K8S_NAMESPACE

      - name: Deploy with Helm
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          helm upgrade --install $HELM_RELEASE ./helm/hello-world \
            --namespace $K8S_NAMESPACE \
            --set image.repository=$ECR_REGISTRY/$ECR_REPOSITORY \
            --set image.tag=$IMAGE_TAG \
            --wait \
            --timeout 5m

      - name: Verify rollout
        run: |
          kubectl rollout status \
            deployment/$HELM_RELEASE \
            -n $K8S_NAMESPACE \
            --timeout=180s

          kubectl get pods \
            -n $K8S_NAMESPACE

      - name: Show application URL
        run: |
          kubectl get ingress \
            -n $K8S_NAMESPACE